---
title: "Biostat 203B Homework 1"
author: Zian ZHUANG
subtitle: Due Feb 10 @ 11:59PM
output:
  html_document:
    highlight: pygments
    toc: yes
    toc_float: yes
---

<!-- Setup -->
<style type="text/css">
body{ /* Normal  */
      font-size: 17px;
      font-family: "Times New Roman";
  }
h1,h2,h3,h4,h5,h6{
  font-family: "Times New Roman";
}
</style>
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, cache.lazy = FALSE)
library(tidyverse)
library(data.table)
library(lubridate)
library(magrittr)
```
<!-- Begin writing -->

Display machine information for reproducibility:
```{r}
sessionInfo()
```


```{r}
os <- sessionInfo()$running
if (str_detect(os, "Linux")) {
  mimic_path <- "/usr/203b-data/mimic-iv"
} else if (str_detect(os, "Windows")) {
  mimic_path <- "."
}
```
Use tidyverse (ggpot2, dplyr) to explore the [MIMIC-IV](https://mimic-iv.mit.edu) data introduced in [homework 1](https://ucla-biostat203b-2021winter.github.io/hw/hw1/hw1.html).


<div class="tocify-extend-page" data-unique="tocify-extend-page" style="height: 0;"></div>