shinyServer(function(input, output, session){
  source("tabs/server/home.R", local = TRUE)
  source("tabs/server/demographic/dgenral.R", local = TRUE)
  source("tabs/server/demographic/dgroup.R", local = TRUE)
  source("tabs/server/demographic/dcorrelation.R", local = TRUE)
  source("tabs/server/lab/labdescrip.R", local = TRUE)
  source("tabs/server/lab/labdensity.R", local = TRUE)
  source("tabs/server/lab/labcorrelation.R", local = TRUE)
  source("tabs/server/vital/vcorrelation.R", local = TRUE)
  source("tabs/server/vital/vdensity.R", local = TRUE)
  source("tabs/server/vital/vdescrip.R", local = TRUE)
})